//tealium universal tag - utag.119 ut4.0.202508221542, Copyright 2025 Tealium.com Inc. All Rights Reserved.
window.dm=window.dm||{AjaxData:[]};window.dm.AjaxEvent=function(et,d,ssid,ad){dm.AjaxData.push({et:et,d:d,ssid:ssid,ad:ad});window.DotMetricsObj&&DotMetricsObj.onAjaxDataUpdate();};window.dm.tagCreated=false;try{(function(id,loader){var u={};utag.o[loader].sender[id]=u;if(utag.ut===undefined){utag.ut={};}
if(utag.ut.loader===undefined){u.loader=function(o){var b,c,l,a=document;if(o.type==="iframe"){b=a.createElement("iframe");o.attrs=o.attrs||{"height":"1","width":"1","style":"display:none"};for(l in utag.loader.GV(o.attrs)){b.setAttribute(l,o.attrs[l]);}b.setAttribute("src",o.src);}else if(o.type=="img"){utag.DB("Attach img: "+o.src);b=new Image();b.src=o.src;return;}else{b=a.createElement("script");b.language="javascript";b.type="text/javascript";b.async=1;b.charset="utf-8";for(l in utag.loader.GV(o.attrs)){b[l]=o.attrs[l];}b.src=o.src;}if(o.id){b.id=o.id};if(typeof o.cb=="function"){if(b.addEventListener){b.addEventListener("load",function(){o.cb()},false);}else{b.onreadystatechange=function(){if(this.readyState=='complete'||this.readyState=='loaded'){this.onreadystatechange=null;o.cb()}};}}l=o.loc||"head";c=a.getElementsByTagName(l)[0];if(c){utag.DB("Attach to "+l+": "+o.src);if(l=="script"){c.parentNode.insertBefore(b,c);}else{c.appendChild(b)}}}}else{u.loader=utag.ut.loader;}
u.ev={view:1};u.initialized=false;u.map={"ipsosSection":"section","page_section":"section1","page_section_2":"section2","page_section_3":"section3","page_section_4":"section4","ipsosDomain":"domain"};u.extend=[function(a,b){try{if(1){if(typeof b.page_section!=='undefined'){if(typeof b.page_name!=='undefined'){if(b.page_section.toLowerCase()==='topics'){b.page_section=b.page_name.toLowerCase();}}}
b.ipsosSection='';if((typeof b.primary_l2!=='undefined')&&b.primary_l2!==''){b.ipsosSection=b.primary_l2;}else if((typeof b.primary_l1!=='undefined')&&b.primary_l1!==''){b.ipsosSection=b.primary_l1;}
}}catch(e){utag.DB(e)}}];u.send=function(a,b){if(u.ev[a]||u.ev.all!==undefined){var c,d,e,f,i;u.data={};for(c=0;c<u.extend.length;c++){try{d=u.extend[c](a,b);if(d==false)return}catch(e){}};for(d in utag.loader.GV(u.map)){if(b[d]!==undefined&&b[d]!==""){e=u.map[d].split(",");for(f=0;f<e.length;f++){u.data[e[f]]=b[d];}}}
var section='';if((typeof u.data.section!=='undefined')&&(u.data.section!=='')){section=u.data.section;}
else{section='other';if((typeof u.data.section4!=='undefined')&&u.data.section4!==''){section=u.data.section4;}else if((typeof u.data.section3!=='undefined')&&u.data.section3!==''){section=u.data.section3;}else if((typeof u.data.section2!=='undefined')&&u.data.section2!==''){section=u.data.section2;}else if((typeof u.data.section1!=='undefined')&&u.data.section1!==''){section=u.data.section1;}}
section=section.toLowerCase();section=section.replace(/[^a-z0-9]/ig,'');section=section.substr(0,50);var hn=document.location.host;if((typeof u.data.domain!=='undefined')&&u.data.domain!==''){hn=u.data.domain;}
if(window.dm.tagCreated===false){let d=document,h=d.getElementsByTagName('head')[0],s=d.createElement('script');s.type='text/javascript';s.async=true;s.src='https://uk-script.dotmetrics.net/door.js?d='+encodeURIComponent(hn)+'&t='+encodeURIComponent(section);h.appendChild(s);window.dm.tagCreated=true;}else{window.dm.AjaxEvent("pageview",null,section);}
}};utag.o[loader].loader.LOAD(id);})("119","newsinternational.thetimes.2018");}catch(error){utag.DB(error);}
